on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test e2e/tests/access.spec.ts
      - uses: actions/upload-artifact@v3
        if: always()
        with:
        name: playwright-report
        path: playwright-report/
        retention-days: 10
